// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyuptgfuolweekawsvcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dXB0Z2Z1b2x3ZWVrYXdzdmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTAzODUsImV4cCI6MjA2NDk4NjM4NX0.pLWgmfUOay2hsgHn-Emt3UI_TfkpCO0Ez5f9cJruWXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);